package FormsPackage;

import ClassesPackage.UserClass;
import ClassesPackage.DataStore;
import ClassesPackage.TeamClass;
import ClassesPackage.UserRole;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author MOATH
 */
public class Users extends javax.swing.JFrame {

    
    private void clearFields() {
    Id.setText("");
    UserName.setText("");
    gmail.setText("");
    Password.setText("");
    ConfirmPassword.setText("");
    Age.setText("");
    JopField.setText("");
    status.setSelected(false);
}
    private void setInterfaceState(String state) {
    boolean isEditing = state.equals("EDIT") || state.equals("ADD");
    UserName.setEnabled(isEditing);
    gmail.setEnabled(isEditing);
    Password.setVisible(isEditing);
    ConfirmPassword.setVisible(isEditing);
    Age.setVisible(isEditing);
    JopField.setEnabled(isEditing);
    Role.setEnabled(isEditing);
    Team.setEnabled(isEditing);
    status.setEnabled(isEditing);
    AddUser.setVisible(state.equals("ADD"));      
    Update.setVisible(state.equals("EDIT"));      
    back.setVisible(isEditing);                   
    NewUser.setVisible(!isEditing);               
    UpdateUser.setVisible(!isEditing);            
    delete.setVisible(!isEditing);                
    jLabel3.setVisible(isEditing); 
    jLabel4.setVisible(isEditing);
    jLabel7.setVisible(isEditing);
}
    /**
     * Creates new form Users
     */
    public Users() {
        initComponents();
        DataStore.initData();
        Team.removeAllItems(); 
        for (TeamClass team : DataStore.teamsList) {
            Team.addItem(team.getName());   
        }
        
        if (DataStore.currentUser != null) {
            Id.setText(String.valueOf(DataStore.currentUser.getId()));
            UserName.setText(DataStore.currentUser.getName());
            gmail.setText(DataStore.currentUser.getEmail());
            Password.setText(DataStore.currentUser.getPass());
            ConfirmPassword.setText(DataStore.currentUser.getPass());
            JopField.setText(DataStore.currentUser.getJobField());
            status.setSelected(DataStore.currentUser.getStatus());
            Team.setSelectedItem(DataStore.currentUser.getTeams());
            
            String roleStr = DataStore.currentUser.getRole().toString();
            for (int i = 0; i < Role.getItemCount(); i++) {
                if (Role.getItemAt(i).toString().equalsIgnoreCase(roleStr)) {
                    Role.setSelectedIndex(i);
                    break;
                }
            }
        }
        
        setInterfaceState("VIEW");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        status = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JopField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        UpdateUser = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        Age = new javax.swing.JTextField();
        gmail = new javax.swing.JTextField();
        Role = new javax.swing.JComboBox();
        UserName = new javax.swing.JTextField();
        ConfirmPassword = new javax.swing.JPasswordField();
        delete = new javax.swing.JButton();
        NewUser = new javax.swing.JButton();
        AddUser = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Task = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showuser = new javax.swing.JTable();
        search = new javax.swing.JButton();
        Task1 = new javax.swing.JButton();
        Id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Team = new javax.swing.JComboBox();
        Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Manegment");

        jLabel2.setText("Gmail");

        jLabel3.setText("Password");

        jLabel4.setText("Confirm Password");

        jLabel5.setText("Role");

        jLabel6.setText("Status");

        jLabel7.setText("Age");

        jLabel8.setText("Jop Field");

        jLabel1.setText("Name");

        UpdateUser.setText("Update");
        UpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserActionPerformed(evt);
            }
        });

        back.setText("Cancel");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Age.setToolTipText("");

        Role.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Volunter", "Supervisior", "Admin" }));
        Role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleActionPerformed(evt);
            }
        });

        ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordActionPerformed(evt);
            }
        });
        ConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfirmPasswordFocusLost(evt);
            }
        });

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        NewUser.setText("AddUser");
        NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserActionPerformed(evt);
            }
        });

        AddUser.setText("Add");
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });

        jLabel9.setText("Search");

        Task.setText("Task Form");
        Task.setToolTipText("");
        Task.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskActionPerformed(evt);
            }
        });

        showuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Email", "Role", "JopField", "Team", "Age", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(showuser);

        search.setText("Show User");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        Task1.setText("Team Form");
        Task1.setToolTipText("");
        Task1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task1ActionPerformed(evt);
            }
        });

        Id.setEditable(false);

        jLabel10.setText("Id");

        Team.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "team 1", "team 2", "team 3", "team 4" }));
        Team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamActionPerformed(evt);
            }
        });

        Update.setText("Update User");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(99, 99, 99))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(100, 100, 100)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel10)
                                .addGap(84, 84, 84)
                                .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Role, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JopField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(29, 29, 29))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(status))
                    .addComponent(ConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(gmail)
                    .addComponent(Age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Task, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Task1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(AddUser)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Team, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(search)
                        .addGap(121, 121, 121))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(UpdateUser)
                        .addGap(63, 63, 63)
                        .addComponent(delete)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(41, 41, 41)
                        .addComponent(UserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(Update)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(gmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(NewUser)
                                                    .addComponent(jLabel2))
                                                .addGap(35, 35, 35)
                                                .addComponent(Task)
                                                .addGap(35, 35, 35)
                                                .addComponent(Task1))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(37, 37, 37))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(status)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(88, 88, 88)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(Role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JopField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))))
                                .addGap(45, 45, 45)))
                        .addComponent(Team, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddUser)
                            .addComponent(back))))
                .addGap(5, 5, 5)
                .addComponent(Update)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(UserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(search)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateUser)
                    .addComponent(delete))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserActionPerformed

        int selectedRow=  showuser.getSelectedRow();
        if(selectedRow == -1)
        {
        JOptionPane.showMessageDialog(this, "Please select a user from the table first!");
        return;
        }
        
         setInterfaceState("EDIT");
         int idToUpdate = Integer.parseInt(showuser.getValueAt(selectedRow, 0).toString());
         UserClass selectedUser = null;
         for (UserClass u : DataStore.usersList) {
             if (u.getId() == idToUpdate) {
                 selectedUser = u;
                 break;
             }
         }
         
         if (selectedUser != null) {
             Id.setText(String.valueOf(selectedUser.getId()));
             UserName.setText(selectedUser.getName());
             gmail.setText(selectedUser.getEmail());
             Password.setText(selectedUser.getPass());
             ConfirmPassword.setText(selectedUser.getPass());
             JopField.setText(selectedUser.getJobField());
             Team.setSelectedItem(selectedUser.getTeams());
             Age.setText(String.valueOf(selectedUser.getAge()));
             status.setSelected(selectedUser.getStatus());
             
             String roleStr = selectedUser.getRole().toString();
             for (int i = 0; i < Role.getItemCount(); i++) {
                 if (Role.getItemAt(i).toString().equalsIgnoreCase(roleStr)) {
                     Role.setSelectedIndex(i);
                     break;
                 }
             }
         }
    }//GEN-LAST:event_UpdateUserActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         setInterfaceState("VIEW");
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int selectedRow = showuser.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a user to delete!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure?");
    if (confirm == JOptionPane.YES_OPTION) {
        
        int idToDelete = Integer.parseInt(showuser.getValueAt(selectedRow, 0).toString());
        
        
        for (int i = 0; i < DataStore.usersList.size(); i++) {
            if (DataStore.usersList.get(i).getId() == idToDelete) {
                DataStore.usersList.remove(i);
                break;
            }
        }
        
        
        searchActionPerformed(null);
        JOptionPane.showMessageDialog(this, "User Deleted.");
    }
        
    }//GEN-LAST:event_deleteActionPerformed
    private void NextId() {
    int nextId = 1;
    if (!DataStore.usersList.isEmpty()) 
        nextId = DataStore.usersList.get(DataStore.usersList.size() - 1).getId() + 1;
    
    Id.setText(String.valueOf(nextId));
}
    private void NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserActionPerformed
        clearFields();
        setInterfaceState("ADD");
       NextId();
    }//GEN-LAST:event_NewUserActionPerformed

    
    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
        try {
        if (UserName.getText().isEmpty() || Password.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Please fill all required fields (Id, Name, Password)!");
            return;
        }
        if (Team.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a Team first!");
            return;
        }
    int id = Integer.parseInt(Id.getText());
    String name = UserName.getText();
    String email = gmail.getText();
    String password = new String(Password.getPassword());
    String confirm = new String(ConfirmPassword.getPassword());
    String job = JopField.getText();
    UserRole role = UserRole.valueOf(Role.getSelectedItem().toString().toUpperCase());
    boolean Status = status.isSelected();
    String team = Team.getSelectedItem().toString();
    int age = 0;
    try {
        age = Integer.parseInt(Age.getText());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Age must be a valid number!");
        return;
    }
    
     UserClass newUser = new UserClass(id,name,email,password,confirm,job,role,Status,team,age);
     DataStore.usersList.add(newUser);
     JOptionPane.showMessageDialog(this, "User Added Successfully!");
     searchActionPerformed(null);  
     clearFields();
     setInterfaceState("VIEW");
        }
        catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID must be a number!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_AddUserActionPerformed

    private void TaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskActionPerformed
            new Tasks().setVisible(true);
            this.dispose(); 
    }//GEN-LAST:event_TaskActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        DefaultTableModel model = (DefaultTableModel) showuser.getModel();
        model.setRowCount(0);
        String searchText = UserSearch.getText().trim();
        boolean found = false;
        for (UserClass user : DataStore.usersList)
            if (searchText.isEmpty() || user.getName().toLowerCase().contains(searchText.toLowerCase())) {
                Object[] row = {
                    user.getId(),     
                    user.getName(),   
                    user.getEmail(),   
                    user.getRole(),     
                    user.getJobField(),
                    user.getTeams(),
                    user.getAge(),
                    user.getStatus()
                };
                model.addRow(row);
                found = true;
                        };
                        if (!found && !searchText.isEmpty()) 
            JOptionPane.showMessageDialog(this, "No user found with this name!");
    }//GEN-LAST:event_searchActionPerformed

    private void Task1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Task1ActionPerformed
         new Teams().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_Task1ActionPerformed

    private void ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordActionPerformed
        
    }//GEN-LAST:event_ConfirmPasswordActionPerformed

    private void ConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPasswordFocusLost
        String p1 = new String(Password.getPassword());
    String p2 = new String(ConfirmPassword.getPassword());
    
    if (!p1.equals(p2) && !p2.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Passwords do not match!", "Security Error", JOptionPane.ERROR_MESSAGE);
        ConfirmPassword.setText(""); 
    }
    }//GEN-LAST:event_ConfirmPasswordFocusLost

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
    if (Id.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a user to update first!");
        return;
    }

    int targetId = Integer.parseInt(Id.getText());
    int foundIndex = -1;
    UserClass oldUser = null;
    for (int i = 0; i < DataStore.usersList.size(); i++) {
        if (DataStore.usersList.get(i).getId() == targetId) {
            foundIndex = i;
            oldUser = DataStore.usersList.get(i);
            break;
        }
    }

    if (foundIndex != -1 && oldUser != null) {
        String name = UserName.getText();
        String email = gmail.getText();
        String job = JopField.getText();
        UserRole role = UserRole.valueOf(Role.getSelectedItem().toString().toUpperCase()); 
        
        boolean isStatus = status.isSelected();
        String team = Team.getSelectedItem().toString();
        int age = 0;
        try {
            age = Integer.parseInt(Age.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Age must be a valid number!");
            return;
        }
        
        String oldPass = oldUser.getPass();
        UserClass updatedUser = new UserClass(
            targetId, 
            name, 
            email, 
            oldPass,
            oldPass,
            job, 
            role, 
            isStatus, 
            team,
            age
        );

        
        DataStore.usersList.set(foundIndex, updatedUser);

        JOptionPane.showMessageDialog(this, "User updated successfully!");
        searchActionPerformed(null); 
        clearFields();
        setInterfaceState("VIEW");
        
    } else 
        JOptionPane.showMessageDialog(this, "Error: User not found!");
    
    }//GEN-LAST:event_UpdateActionPerformed

    private void TeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamActionPerformed

    private void RoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUser;
    private javax.swing.JTextField Age;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField JopField;
    private javax.swing.JButton NewUser;
    private javax.swing.JPasswordField Password;
    private javax.swing.JComboBox Role;
    private javax.swing.JButton Task;
    private javax.swing.JButton Task1;
    private javax.swing.JComboBox Team;
    private javax.swing.JButton Update;
    private javax.swing.JButton UpdateUser;
    private javax.swing.JTextField UserName;
    private javax.swing.JTextField UserSearch;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JTextField gmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JTable showuser;
    private javax.swing.JCheckBox status;
    // End of variables declaration//GEN-END:variables
}
